name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - head
          - 3.0 # ruby 3
          - 2.7

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Set up dependencies
      run: sudo apt install graphviz && gem install ruby-graphviz
    - name: Run the default task
      run: bundle exec rake
